# Generated by Django 5.2.12 on 2026-03-15 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "competences",
            "0002_alter_skillresource_options_skillresource_content_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        help_text="Décrivez votre parcours et expertise",
                        verbose_name="Présentation",
                    ),
                ),
                (
                    "specialties",
                    models.JSONField(
                        default=list, help_text='Ex: ["Python", "Marketing digital"]'
                    ),
                ),
                (
                    "university",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Université"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Disponible"),
                ),
                (
                    "hourly_rate_fcfa",
                    models.IntegerField(
                        default=500, verbose_name="Tarif / 30 min (FCFA)"
                    ),
                ),
                (
                    "total_sessions",
                    models.IntegerField(default=0, verbose_name="Sessions effectuées"),
                ),
                (
                    "average_rating",
                    models.FloatField(default=0.0, verbose_name="Note moyenne"),
                ),
                (
                    "total_reviews",
                    models.IntegerField(default=0, verbose_name="Nombre d'avis"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil mentor",
                "verbose_name_plural": "Profils mentors",
            },
        ),
        migrations.CreateModel(
            name="MentorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("visio", "Visioconférence"),
                            ("chat", "Chat en ligne"),
                            ("presentiel", "Présentiel"),
                        ],
                        default="chat",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("completed", "Terminée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "time_slot",
                    models.CharField(max_length=20, verbose_name="Créneau horaire"),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(default=30, verbose_name="Durée (min)"),
                ),
                (
                    "price_fcfa",
                    models.IntegerField(default=0, verbose_name="Prix (FCFA)"),
                ),
                (
                    "is_free_intro",
                    models.BooleanField(
                        default=False, verbose_name="Session découverte gratuite"
                    ),
                ),
                (
                    "topic",
                    models.CharField(blank=True, max_length=300, verbose_name="Sujet"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notes de session"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mentee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentee_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="mentorat.mentorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session de mentorat",
                "verbose_name_plural": "Sessions de mentorat",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(verbose_name="Note (1-5)")),
                ("comment", models.TextField(blank=True, verbose_name="Commentaire")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="mentorat.mentorsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avis mentor",
                "verbose_name_plural": "Avis mentors",
            },
        ),
        migrations.CreateModel(
            name="StudyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "max_members",
                    models.IntegerField(default=10, verbose_name="Places max"),
                ),
                (
                    "price_per_member_fcfa",
                    models.IntegerField(
                        default=500, verbose_name="Prix par membre (FCFA)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_groups",
                        to="mentorat.mentorprofile",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="competences.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Groupe d'étude",
                "verbose_name_plural": "Groupes d'étude",
            },
        ),
        migrations.CreateModel(
            name="StudyGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="mentorat.studygroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre du groupe",
                "verbose_name_plural": "Membres du groupe",
                "unique_together": {("group", "user")},
            },
        ),
    ]
