# Generated by Django 5.2.11 on 2026-02-22 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competences', '0001_initial'),
        ('gamification', '0001_initial'),
        ('parcours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_fcfa', models.IntegerField(verbose_name='Montant (FCFA)')),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money (MTN)'), ('orange_money', 'Orange Money'), ('carte', 'Carte bancaire')], default='mobile_money', max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('holder_name', models.CharField(blank=True, max_length=100, verbose_name='Nom du titulaire')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='gamification.booster')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='competences.skill')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='parcours.careerstep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulation de paiement',
                'verbose_name_plural': 'Simulations de paiement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_percent', models.FloatField(default=0.0, verbose_name='Progression %')),
                ('completed_steps', models.ManyToManyField(blank=True, related_name='completed_by', to='parcours.careerstep')),
                ('unlocked_steps', models.ManyToManyField(blank=True, related_name='unlocked_by', to='parcours.careerstep')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression utilisateur',
                'verbose_name_plural': 'Progressions utilisateurs',
            },
        ),
    ]
