# Generated by Django 5.2.11 on 2026-02-22 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(default='💡', max_length=10)),
                ('max_level', models.IntegerField(default=5, verbose_name='Niveau max')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('price_fcfa', models.IntegerField(default=0, verbose_name='Prix (FCFA)')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
            },
        ),
        migrations.CreateModel(
            name='SkillResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('resource_type', models.CharField(choices=[('video', 'Vidéo'), ('pdf', 'PDF'), ('mini_formation', 'Mini-formation'), ('exercice', 'Exercice pratique')], default='video', max_length=30)),
                ('url', models.URLField(blank=True, verbose_name='Lien')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='Durée (min)')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='competences.skill')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
            },
        ),
        migrations.CreateModel(
            name='UserSkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(default=0, verbose_name='Niveau actuel')),
                ('progress_percent', models.FloatField(default=0.0, verbose_name='Progression %')),
                ('unlocked', models.BooleanField(default=False, verbose_name='Débloqué')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='competences.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression compétence',
                'verbose_name_plural': 'Progressions compétences',
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
