# Generated by Django 5.2.11 on 2026-02-22 22:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillresource',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Ressource', 'verbose_name_plural': 'Ressources'},
        ),
        migrations.AddField(
            model_name='skillresource',
            name='content',
            field=models.TextField(blank=True, help_text='Contenu texte pour les tutoriels intégrés', verbose_name='Contenu du tutoriel'),
        ),
        migrations.AddField(
            model_name='skillresource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillresource',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='skillresource',
            name='file',
            field=models.FileField(blank=True, upload_to='resources/pdf/', verbose_name='Fichier PDF'),
        ),
        migrations.AddField(
            model_name='skillresource',
            name='is_free_preview',
            field=models.BooleanField(default=False, help_text='Accessible même sans paiement', verbose_name='Aperçu gratuit'),
        ),
        migrations.AddField(
            model_name='skillresource',
            name='level',
            field=models.CharField(choices=[('debutant', '🟢 Débutant'), ('intermediaire', '🟡 Intermédiaire'), ('avance', '🔴 Avancé')], default='debutant', max_length=20, verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='skillresource',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Ordre'),
        ),
        migrations.AddField(
            model_name='skillresource',
            name='xp_reward',
            field=models.IntegerField(default=25, verbose_name='XP gagné'),
        ),
        migrations.AlterField(
            model_name='skillresource',
            name='resource_type',
            field=models.CharField(choices=[('video', '🎬 Vidéo'), ('pdf', '📄 Document PDF'), ('tutoriel', '📝 Tutoriel'), ('lien', '🔗 Lien externe'), ('exercice', '✏️ Exercice pratique'), ('mini_formation', '🎓 Mini-formation')], default='video', max_length=30),
        ),
        migrations.AlterField(
            model_name='skillresource',
            name='url',
            field=models.URLField(blank=True, verbose_name='Lien externe'),
        ),
        migrations.CreateModel(
            name='UserResourceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Terminé')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de completion')),
                ('notes', models.TextField(blank=True, verbose_name='Notes personnelles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_completions', to='competences.skillresource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression ressource',
                'verbose_name_plural': 'Progressions ressources',
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
