# Generated by Django 5.2.11 on 2026-02-22 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('tags', models.JSONField(default=list, help_text='Ex: ["Informatique", "Web"]')),
                ('icon', models.CharField(default='💼', max_length=10)),
                ('skills', models.ManyToManyField(blank=True, related_name='career_paths', to='competences.skill')),
            ],
            options={
                'verbose_name': 'Parcours de carrière',
                'verbose_name_plural': 'Parcours de carrière',
            },
        ),
        migrations.CreateModel(
            name='CareerStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_free', models.BooleanField(default=False, verbose_name='Gratuit')),
                ('price_fcfa', models.IntegerField(default=0, verbose_name='Prix (FCFA)')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('duration_hours', models.IntegerField(default=0, verbose_name='Durée (heures)')),
                ('features', models.JSONField(default=list, help_text='Ex: ["Cours vidéo 12h", "8 projets"]')),
                ('icon', models.CharField(default='📘', max_length=10)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='parcours.careerpath')),
            ],
            options={
                'verbose_name': 'Étape de carrière',
                'verbose_name_plural': 'Étapes de carrière',
                'ordering': ['career', 'order'],
            },
        ),
    ]
