# Generated by Django 5.2.12 on 2026-03-15 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcours", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StepProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre du projet"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "project_url",
                    models.URLField(blank=True, verbose_name="Lien du projet"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Soumis"),
                            ("reviewing", "En révision"),
                            ("approved", "Approuvé"),
                            ("needs_revision", "À réviser"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="parcours.careerstep",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet d'étape",
                "verbose_name_plural": "Projets d'étape",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StepCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_code", models.CharField(max_length=30, unique=True)),
                ("share_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="parcours.careerstep",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificat",
                "verbose_name_plural": "Certificats",
                "unique_together": {("user", "step")},
            },
        ),
        migrations.CreateModel(
            name="PeerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(verbose_name="Note (1-5)")),
                ("feedback", models.TextField(verbose_name="Commentaire")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_reviews",
                        to="parcours.stepproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revue par les pairs",
                "verbose_name_plural": "Revues par les pairs",
                "unique_together": {("project", "reviewer")},
            },
        ),
    ]
