# Generated by Django 5.2.12 on 2026-03-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="has_seen_inventory_tutorial",
            field=models.BooleanField(
                default=False,
                help_text="Ne plus afficher le tutoriel interactif du Module 3 Inventaire.",
                verbose_name="A vu le tutoriel inventaire",
            ),
        ),
    ]
