# Generated by Django 5.2.12 on 2026-03-15 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("content", models.TextField(verbose_name="Votre témoignage")),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Entreprise / Stage"
                    ),
                ),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("emploi", "Emploi trouvé"),
                            ("stage", "Stage obtenu"),
                            ("freelance", "Mission freelance"),
                            ("projet", "Projet réussi"),
                            ("competence", "Compétence acquise"),
                        ],
                        default="emploi",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Mis en avant"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Témoignage",
                "verbose_name_plural": "Témoignages",
                "ordering": ["-created_at"],
            },
        ),
    ]
