# Generated by Django 5.2.12 on 2026-03-21 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("icon", models.CharField(default="📦", max_length=10)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Catégorie d'actif",
                "verbose_name_plural": "Catégories d'actif",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amn_tag",
                    models.CharField(
                        help_text="Identifiant unique AMN (ex: AMN-PC-0042)",
                        max_length=50,
                        unique=True,
                        verbose_name="Tag AMN",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Désignation")),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="Marque"),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="Modèle"),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="N° Série"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("assigned", "Assigné"),
                            ("maintenance", "En maintenance"),
                            ("retired", "Mis hors service"),
                            ("lost", "Perdu / Volé"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'attribution"
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'achat"
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valeur d'achat (FCFA)",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Localisation"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        upload_to="inventory/qr_codes/",
                        verbose_name="QR Code",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_assets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigné à",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="inventory.assetcategory",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actif",
                "verbose_name_plural": "Actifs",
                "ordering": ["amn_tag"],
            },
        ),
        migrations.CreateModel(
            name="AssetTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Motif du transfert")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Refusé"),
                            ("completed", "Complété"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approuvé par",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="inventory.asset",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cédant",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bénéficiaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfert d'actif",
                "verbose_name_plural": "Transferts d'actifs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Désignation")),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        help_text="Laissez vide pour génération automatique",
                        max_length=50,
                        unique=True,
                        verbose_name="Référence SKU",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité actuelle"
                    ),
                ),
                (
                    "alert_threshold",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Déclenche une alerte si la quantité descend en dessous",
                        verbose_name="Seuil d'alerte",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("unit", "Unité"),
                            ("box", "Boîte"),
                            ("ream", "Ramette"),
                            ("liter", "Litre"),
                            ("kg", "Kg"),
                            ("pack", "Pack"),
                        ],
                        default="unit",
                        max_length=10,
                        verbose_name="Unité",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Emplacement"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Fournisseur"
                    ),
                ),
                (
                    "last_restock_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Dernier réappro"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_items",
                        to="inventory.assetcategory",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article en stock",
                "verbose_name_plural": "Articles en stock",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("in", "Entrée"),
                            ("out", "Sortie"),
                            ("adjust", "Ajustement"),
                            ("loss", "Perte / Casse"),
                        ],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Positif pour entrée, négatif pour sortie",
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "quantity_before",
                    models.PositiveIntegerField(default=0, verbose_name="Stock avant"),
                ),
                (
                    "quantity_after",
                    models.PositiveIntegerField(default=0, verbose_name="Stock après"),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=255, verbose_name="Motif"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="N° BL, N° commande, etc.",
                        max_length=100,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date/Heure"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="inventory.stockitem",
                        verbose_name="Article",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Effectué par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
                "ordering": ["-timestamp"],
                "default_permissions": ("add", "view"),
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="N° Ticket",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Sujet")),
                (
                    "description",
                    models.TextField(verbose_name="Description du problème"),
                ),
                (
                    "breakdown_photo",
                    models.ImageField(
                        blank=True,
                        upload_to="inventory/tickets/",
                        verbose_name="Photo de la panne",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hardware", "Matériel informatique"),
                            ("software", "Logiciel / Application"),
                            ("network", "Réseau / Internet"),
                            ("phone", "Téléphonie"),
                            ("furniture", "Mobilier / Locaux"),
                            ("other", "Autre"),
                        ],
                        default="hardware",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyenne"),
                            ("high", "Haute"),
                            ("critical", "Critique / SOS"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ouvert"),
                            ("in_progress", "En cours"),
                            ("waiting", "En attente de pièces"),
                            ("resolved", "Résolu"),
                            ("closed", "Fermé"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="Notes de résolution"),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigné à",
                    ),
                ),
                (
                    "related_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="inventory.asset",
                        verbose_name="Actif concerné",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Soumis par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Support",
                "verbose_name_plural": "Tickets Support",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Commentaire")),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="Si coché, visible uniquement par le staff",
                        verbose_name="Note interne",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="inventory.ticket",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire ticket",
                "verbose_name_plural": "Commentaires tickets",
                "ordering": ["created_at"],
            },
        ),
    ]
