# Generated by Django 5.2.12 on 2026-03-15 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "competences",
            "0002_alter_skillresource_options_skillresource_content_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MicroLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "content",
                    models.TextField(
                        verbose_name="Contenu (max 500 caractères recommandés)"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("free", "Gratuit"), ("premium", "Premium")],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Ordre d'envoi")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="competences.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Micro-leçon",
                "verbose_name_plural": "Micro-leçons",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ShareableResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("career_name", models.CharField(max_length=200)),
                ("match_percentage", models.IntegerField()),
                ("share_code", models.CharField(max_length=20, unique=True)),
                ("views_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shareable_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat partageable",
                "verbose_name_plural": "Résultats partageables",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Numéro WhatsApp"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="Nom"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False, verbose_name="Premium (micro-lessons)"
                    ),
                ),
                (
                    "daily_lesson_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Leçons quotidiennes"
                    ),
                ),
                (
                    "reminder_enabled",
                    models.BooleanField(default=True, verbose_name="Rappels activés"),
                ),
                (
                    "current_quiz_step",
                    models.IntegerField(
                        default=0, help_text="Étape actuelle du quiz d'orientation"
                    ),
                ),
                (
                    "quiz_answers",
                    models.JSONField(
                        default=dict, help_text="Réponses au quiz en cours"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonné WhatsApp",
                "verbose_name_plural": "Abonnés WhatsApp",
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("incoming", "Reçu"), ("outgoing", "Envoyé")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        default="text",
                        help_text="text, quiz, lesson, reminder, result",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="whatsapp_bot.whatsappsubscriber",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message WhatsApp",
                "verbose_name_plural": "Messages WhatsApp",
                "ordering": ["-created_at"],
            },
        ),
    ]
