# Generated by Django 5.2.12 on 2026-03-20 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(default=0, verbose_name="Durée (min)"),
                ),
                (
                    "instructor_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Formateur"
                    ),
                ),
                (
                    "instructor_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Titre du formateur"
                    ),
                ),
                (
                    "cover_image_url",
                    models.URLField(blank=True, verbose_name="Image (URL)"),
                ),
                (
                    "xp_reward",
                    models.PositiveIntegerField(
                        default=50, verbose_name="XP à la complétion"
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cours",
                "verbose_name_plural": "Cours",
                "ordering": ["module", "order"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="🏢", max_length=10)),
                (
                    "head_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Responsable"
                    ),
                ),
            ],
            options={
                "verbose_name": "Département",
                "verbose_name_plural": "Départements",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("video", "🎬 Vidéo"),
                            ("article", "📄 Article"),
                            ("quiz", "❓ Quiz"),
                            ("exercise", "✏️ Exercice"),
                            ("pdf", "📋 PDF"),
                            ("live", "📡 Présentiel/Live"),
                        ],
                        default="article",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                ("video_url", models.URLField(blank=True, verbose_name="URL vidéo")),
                ("pdf_url", models.URLField(blank=True, verbose_name="URL PDF")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(default=15, verbose_name="Durée (min)"),
                ),
                ("xp_reward", models.PositiveIntegerField(default=20)),
                (
                    "is_free_preview",
                    models.BooleanField(default=False, verbose_name="Aperçu gratuit"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="learning.course",
                        verbose_name="Cours",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leçon",
                "verbose_name_plural": "Leçons",
                "ordering": ["course", "order"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "passing_score",
                    models.PositiveIntegerField(
                        default=70, verbose_name="Score minimum (%)"
                    ),
                ),
                (
                    "time_limit_minutes",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Limite de temps (min)"
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Tentatives max"
                    ),
                ),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="learning.lesson",
                        verbose_name="Leçon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quiz",
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0.0, verbose_name="Score (%)")),
                ("passed", models.BooleanField(default=False)),
                (
                    "answers",
                    models.JSONField(
                        default=dict, help_text="Réponses choisies par question"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="learning.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tentative de quiz",
                "verbose_name_plural": "Tentatives de quiz",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Question")),
                (
                    "explanation",
                    models.TextField(
                        blank=True, verbose_name="Explication de la réponse"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("points", models.PositiveIntegerField(default=1)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="learning.quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question de quiz",
                "verbose_name_plural": "Questions de quiz",
                "ordering": ["quiz", "order"],
            },
        ),
        migrations.CreateModel(
            name="QuizChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="Réponse")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Correcte"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="learning.quizquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Choix de réponse",
                "verbose_name_plural": "Choix de réponse",
                "ordering": ["question", "order"],
            },
        ),
        migrations.CreateModel(
            name="TrainingModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(verbose_name="Numéro du module"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debutant", "Débutant"),
                            ("intermediaire", "Intermédiaire"),
                            ("avance", "Avancé"),
                        ],
                        default="debutant",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("published", "Publié"),
                            ("archived", "Archivé"),
                        ],
                        default="published",
                        max_length=20,
                    ),
                ),
                (
                    "duration_hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Durée estimée (heures)"
                    ),
                ),
                (
                    "objectives",
                    models.JSONField(
                        default=list, help_text="Liste des objectifs pédagogiques"
                    ),
                ),
                (
                    "prerequisites",
                    models.TextField(blank=True, verbose_name="Prérequis"),
                ),
                (
                    "cover_image_url",
                    models.URLField(
                        blank=True, verbose_name="Image de couverture (URL)"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False, verbose_name="Formation obligatoire"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modules",
                        to="learning.department",
                        verbose_name="Département",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module de formation",
                "verbose_name_plural": "Modules de formation",
                "ordering": ["order", "number"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Inscrit"),
                            ("in_progress", "En cours"),
                            ("completed", "Terminé"),
                            ("dropped", "Abandonné"),
                        ],
                        default="enrolled",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "progress_percent",
                    models.FloatField(default=0.0, verbose_name="Progression (%)"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière activité"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="learning.trainingmodule",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription",
                "verbose_name_plural": "Inscriptions",
                "ordering": ["-enrolled_at"],
                "unique_together": {("user", "module")},
            },
        ),
        migrations.AddField(
            model_name="course",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="learning.trainingmodule",
                verbose_name="Module",
            ),
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_number", models.CharField(max_length=50, unique=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "score",
                    models.FloatField(default=0.0, verbose_name="Score final (%)"),
                ),
                ("is_valid", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="learning.enrollment",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="learning.trainingmodule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificat",
                "verbose_name_plural": "Certificats",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "time_spent_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Temps passé (min)"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notes personnelles"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="learning.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Progression leçon",
                "verbose_name_plural": "Progressions leçons",
                "unique_together": {("user", "lesson")},
            },
        ),
    ]
