# Generated by Django 5.2.11 on 2026-02-22 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('icon', models.CharField(default='🏅', max_length=10)),
                ('category', models.CharField(choices=[('progression', 'Progression'), ('regularite', 'Régularité'), ('excellence', 'Excellence'), ('social', 'Social'), ('special', 'Spécial')], default='progression', max_length=30)),
                ('condition_type', models.CharField(choices=[('xp_total', 'XP total atteint'), ('level_reached', 'Niveau atteint'), ('test_complete', 'Test complété'), ('steps_completed', 'Étapes complétées'), ('streak_days', 'Jours consécutifs'), ('skills_unlocked', 'Compétences débloquées'), ('payment_made', 'Paiement effectué')], default='xp_total', max_length=30)),
                ('condition_value', models.IntegerField(default=0, help_text='Seuil numérique')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
            },
        ),
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(default='🚀', max_length=10)),
                ('booster_type', models.CharField(choices=[('xp_multiplier', 'Multiplicateur XP'), ('ai_analysis', 'Analyse IA Pro'), ('pack_competences', 'Pack Compétences'), ('theme', 'Thème Profil'), ('pack_ambassadeur', 'Pack Ambassadeur')], default='xp_multiplier', max_length=30)),
                ('price_fcfa', models.IntegerField(verbose_name='Prix (FCFA)')),
                ('duration_days', models.IntegerField(default=0, help_text='0 = permanent')),
                ('multiplier', models.FloatField(default=1.0, help_text='Multiplicateur XP (ex: 2.0)')),
            ],
            options={
                'verbose_name': 'Booster',
                'verbose_name_plural': 'Boosters',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('xp_reward', models.IntegerField(default=200, verbose_name='Récompense XP')),
                ('start_date', models.DateField(verbose_name='Début')),
                ('end_date', models.DateField(verbose_name='Fin')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Défi',
                'verbose_name_plural': 'Défis',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserBooster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='gamification.booster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booster utilisateur',
                'verbose_name_plural': 'Boosters utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('xp_earned', models.IntegerField(verbose_name='XP gagnés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement XP',
                'verbose_name_plural': 'Événements XP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Badge utilisateur',
                'verbose_name_plural': 'Badges utilisateurs',
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='gamification.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
