# Generated by Django 5.2.12 on 2026-03-20 23:33

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "🏖️ Congé annuel"),
                            ("sick", "🤒 Congé maladie"),
                            ("maternity", "👶 Congé maternité/paternité"),
                            ("unpaid", "💼 Congé sans solde"),
                            ("training", "🎓 Formation externe"),
                            ("emergency", "🆘 Urgence familiale"),
                            ("other", "📋 Autre"),
                        ],
                        default="annual",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                ("reason", models.TextField(verbose_name="Motif")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "⏳ En attente"),
                            ("approved", "✅ Approuvé"),
                            ("rejected", "❌ Refusé"),
                            ("cancelled", "🚫 Annulé"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(blank=True, verbose_name="Commentaire RH"),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_leaves",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Traité par",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de congé",
                "verbose_name_plural": "Demandes de congé",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("matin", "Matin (07h-15h)"),
                            ("journee", "Journée (08h-17h)"),
                            ("apres_midi", "Après-midi (13h-21h)"),
                            ("nuit", "Nuit (21h-06h)"),
                            ("flexible", "Flexible"),
                        ],
                        default="journee",
                        max_length=20,
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        default=datetime.time(8, 0), verbose_name="Heure de début"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        default=datetime.time(17, 0), verbose_name="Heure de fin"
                    ),
                ),
                ("monday", models.BooleanField(default=True)),
                ("tuesday", models.BooleanField(default=True)),
                ("wednesday", models.BooleanField(default=True)),
                ("thursday", models.BooleanField(default=True)),
                ("friday", models.BooleanField(default=True)),
                ("saturday", models.BooleanField(default=False)),
                ("sunday", models.BooleanField(default=False)),
                ("effective_from", models.DateField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planning de travail",
                "verbose_name_plural": "Plannings de travail",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "✅ Présent"),
                            ("absent", "❌ Absent"),
                            ("late", "⚠️ En retard"),
                            ("half_day", "🌗 Demi-journée"),
                            ("remote", "🏠 Télétravail"),
                            ("on_leave", "🏖️ En congé"),
                            ("sick", "🤒 Maladie"),
                            ("holiday", "🎉 Jour férié"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                (
                    "check_in",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure d'arrivée"
                    ),
                ),
                (
                    "check_out",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de départ"
                    ),
                ),
                (
                    "working_hours",
                    models.FloatField(default=0.0, verbose_name="Heures travaillées"),
                ),
                (
                    "overtime_hours",
                    models.FloatField(
                        default=0.0, verbose_name="Heures supplémentaires"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Remarques")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Siège Douala, Agence Yaoundé, Télétravail",
                        max_length=100,
                        verbose_name="Lieu",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employé",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_attendances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Présence",
                "verbose_name_plural": "Présences",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Année")),
                ("month", models.PositiveIntegerField(verbose_name="Mois")),
                ("present_days", models.PositiveIntegerField(default=0)),
                ("absent_days", models.PositiveIntegerField(default=0)),
                ("late_days", models.PositiveIntegerField(default=0)),
                ("leave_days", models.PositiveIntegerField(default=0)),
                ("total_hours", models.FloatField(default=0.0)),
                ("overtime_hours", models.FloatField(default=0.0)),
                (
                    "attendance_rate",
                    models.FloatField(default=0.0, verbose_name="Taux de présence (%)"),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Récap mensuel présence",
                "verbose_name_plural": "Récaps mensuels présence",
                "ordering": ["-year", "-month"],
                "unique_together": {("user", "year", "month")},
            },
        ),
    ]
