# Generated by Django 5.2.11 on 2026-02-22 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrientationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Question')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('category', models.CharField(choices=[('interest', "Centre d'intérêt"), ('workstyle', 'Style de travail'), ('goal', 'Objectif'), ('skill', 'Compétence')], default='interest', max_length=50)),
                ('icon', models.CharField(blank=True, default='❓', max_length=10)),
            ],
            options={
                'verbose_name': "Question d'orientation",
                'verbose_name_plural': "Questions d'orientation",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OrientationChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Texte du choix')),
                ('icon', models.CharField(blank=True, default='', max_length=10)),
                ('weights', models.JSONField(default=dict, help_text='Poids par carrière: {"fullstack": 3, "chef_projet": 1, "data_analyst": 2}')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='orientation.orientationquestion')),
            ],
            options={
                'verbose_name': 'Choix de réponse',
                'verbose_name_plural': 'Choix de réponse',
            },
        ),
        migrations.CreateModel(
            name='OrientationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField(default=dict, help_text='Scores par carrière: {"fullstack": 92, "chef_projet": 78, ...}')),
                ('summary', models.TextField(blank=True, verbose_name='Résumé personnalisé')),
                ('career_projection_3y', models.TextField(blank=True, verbose_name='Projection carrière 3 ans')),
                ('priority_skills', models.JSONField(default=list, help_text='Compétences prioritaires')),
                ('selected_choices', models.JSONField(default=dict, help_text='Réponses: {question_id: choice_id}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_for', to='parcours.careerpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientation_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Résultat d'orientation",
                'verbose_name_plural': "Résultats d'orientation",
                'ordering': ['-created_at'],
            },
        ),
    ]
